name = "notification-consumer-worker"
main = "src/worker.js"
compatibility_date = "2025-08-19"
compatibility_flags = ["nodejs_compat"]



# Hyperdrive binding (Postgres)
[[hyperdrive]]
binding = "DB"
id = "my-postgres-db"

# 👇 Add this for local dev
localConnectionString = "postgresql://cladbetestuser:cladbe%40123@80.65.208.176:5432/cladbedatabase_testing"

# Queue consumer binding
[[queues.consumers]]
queue = "notification-queues"
