name = "notification-consumer-worker"
main = "src/worker.js"
compatibility_date = "2025-08-19"
compatibility_flags = ["nodejs_compat"]
[observability.logs]
enabled = true

# Hyperdrive binding (Postgres)
[[hyperdrive]]
binding = "HYPERDRIVE"
id = "c3e1bf6e888a46a1815dfe02fa7559b1"

# 👇 Add this for local dev
localConnectionString = "postgresql://cladbetestuser:cladbe%40123@80.65.208.176:5432/cladbedatabase_testing"

# Queue consumer binding
[[queues.consumers]]
queue = "notification-queues"

